export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  welcome: '/welcome',
  dashboard: '/dashboard',
  chartOfAccounts: '/chart-of-accounts',
  accounts: '/accounts',
  counterparties: '/counterparties',
  ledger: '/ledger',
  creditCards: '/credit-cards',
  recurrences: '/recurrences',
  projection: '/projection',
  planning: '/planning',
} as const;
